#!/usr/bin/sh




################################################################################
### Head: Path
##

##
## ~/.config/reiver/init
##


##
## ## Link
##
## * https://github.com/samwhelp/ultramarine-river-adjustment/blob/main/prototype/main/river-config/Main/asset/overlay/etc/skel/.config/river/init
## * https://github.com/samwhelp/ultramarine-river-adjustment/blob/main/prototype/main/river-config/Main/asset/overlay/etc/skel/.config/river/autostart
##


##
## ## Example
##
## * https://github.com/riverwm/river/blob/master/example/init
##


##
### Tail: Path
################################################################################




################################################################################
### Head: Note
##

##
## This is the example configuration file for river.
##
## If you wish to edit this, you will probably want to copy it to
## $XDG_CONFIG_HOME/river/init or $HOME/.config/river/init first.
##
## See the river(1), riverctl(1), and rivertile(1) man pages for complete
## documentation.
##

##
### Tail: Note
################################################################################




################################################################################
### Head: Appearance / Settings
##


# Set background and border color
riverctl background-color 0x002b36
riverctl border-color-focused 0x93a1a1
riverctl border-color-unfocused 0x586e75


##
### Tail: Appearance / Settings
################################################################################




################################################################################
### Head: Keybind
##

##
## Note: the "Super" modifier is also known as Logo, GUI, Windows, Mod4, etc.
##

##
## Set keyboard repeat rate
##

riverctl set-repeat 50 300


##
### Tail: Keybind
################################################################################




################################################################################
### Head: Keybind / System / Exit
##


##
## `Alt + Shift + x` to show wlogout
##

riverctl map normal Alt+Shift X spawn wlogout


##
## `Alt + Ctrl + x` to exit river
##

riverctl map normal Alt+Control X exit


##
### Tail: Keybind / System / Exit
################################################################################




################################################################################
### Head: Keybind / Application / Terminal
##

riverctl map normal Alt Return spawn sakura

riverctl map normal Alt+Shift A spawn sakura
riverctl map normal Alt+Control A spawn xfce4-terminal

riverctl map normal Alt+Shift T spawn qterminal
riverctl map normal Alt+Control T spawn foot

##
### Tail: Keybind / Application / Terminal
################################################################################




################################################################################
### Head: Keybind / Application / Favorite
##


riverctl map normal Alt+Shift F spawn pcmanfm-qt
riverctl map normal Alt+Shift G spawn thunar
riverctl map normal Alt+Shift E spawn mousepad
riverctl map normal Alt+Shift B spawn 'firefox --new-tab about:blank'

riverctl map normal Alt+Shift V spawn pavucontrol
#riverctl map normal Alt+Shift V spawn mate-volume-control

riverctl map normal Alt+Shift N spawn nm-connection-editor


##
### Tail: Keybind / Application / Favorite
################################################################################




################################################################################
### Head: Keybind / Application / Rofi
##

riverctl map normal Alt+Shift D spawn 'rofi -show drun -show-icons'
riverctl map normal Alt+Shift R spawn 'rofi -show run -show-icons'
riverctl map normal Alt+Shift W spawn 'rofi -show window -show-icons'

##
### Tail: Keybind / Application / Rofi
################################################################################




################################################################################
### Head: Mousebind / Window / Base
##


##
## `Super + [Left Mouse Button]` to move views
##

riverctl map-pointer normal Super BTN_LEFT move-view


##
## `Super + [Right Mouse Button]` to resize views
##

riverctl map-pointer normal Super BTN_RIGHT resize-view


##
## `Super + [Middle Mouse Button]` to toggle float
##

riverctl map-pointer normal Super BTN_MIDDLE toggle-float


##
### Tail: Mousebind / Window / Base
################################################################################




################################################################################
### Head: Keybind / Window / Base
##


##
## `Super + q` to close the focused view
##

riverctl map normal Super Q close


##
## `Super + v` to toggle float
##

riverctl map normal Super V toggle-float
#riverctl map normal Super N toggle-float


##
## `Super + f` to toggle fullscreen
##

riverctl map normal Super F toggle-fullscreen


##
### Tail: Keybind / Window / Base
################################################################################




################################################################################
### Head: Keybind / Window / Focus
##


##
## `Super + A` and `Super + S` to focus the previous/next view in the layout stack
##

riverctl map normal Super A focus-view previous
riverctl map normal Super S focus-view next


##
### Tail: Keybind / Window / Focus
################################################################################




################################################################################
### Head: Keybind / Window / Swap
##


##
## `Super + Grave` and `Super + Tab` to swap the focused view with the previous/next view in the layout stack
##

riverctl map normal Super Grave swap previous
riverctl map normal Super Tab swap next


##
## `Super + Return` to bump the focused view to the top of the layout stack
##

riverctl map normal Super Return zoom


##
### Tail: Keybind / Window / Swap
################################################################################




################################################################################
### Head: Keybind / Window / Move
##


##
## `Super + {k,j,h,l}` to move views
##

riverctl map normal Super K move up 100
riverctl map normal Super J move down 100
riverctl map normal Super H move left 100
riverctl map normal Super L move right 100


##
### Tail: Keybind / Window / Move
################################################################################




################################################################################
### Head: Keybind / Window / Resize
##


##
## `Super + Control + {k,j,h,l}` to resize views
##

riverctl map normal Super+Control K resize vertical 100
riverctl map normal Super+Control J resize vertical -100
riverctl map normal Super+Control H resize horizontal -100
riverctl map normal Super+Control L resize horizontal 100


##
### Tail: Keybind / Window / Resize
################################################################################




################################################################################
### Head: Keybind / Window / Snap
##


##
## Super + Shift + {k,j,h,l} to snap views to screen edges
##

riverctl map normal Super+Shift K snap up
riverctl map normal Super+Shift J snap down
riverctl map normal Super+Shift H snap left
riverctl map normal Super+Shift L snap right


##
### Tail: Keybind / Window / Move
################################################################################





################################################################################
### Head: Keybind / Tag / Control
##

for i in $(seq 1 9)
do
	tags=$((1 << ($i - 1)))

	# Super+[1-9] to focus tag [0-8]
	riverctl map normal Super $i set-focused-tags $tags

	# Super+Shift+[1-9] to tag focused view with tag [0-8]
	riverctl map normal Super+Shift $i set-view-tags $tags

	# Super+Control+[1-9] to toggle focus of tag [0-8]
	riverctl map normal Super+Control $i toggle-focused-tags $tags

	# Super+Shift+Control+[1-9] to toggle tag [0-8] of focused view
	riverctl map normal Super+Shift+Control $i toggle-view-tags $tags
done

# Super+0 to focus all tags
# Super+Shift+0 to tag focused view with all tags
all_tags=$(((1 << 32) - 1))
riverctl map normal Super 0 set-focused-tags $all_tags
riverctl map normal Super+Shift 0 set-view-tags $all_tags


##
### Tail: Keybind / Tag / Control
################################################################################




################################################################################
### Head: Keybind / Output / Focus
##

##
## Super+Period and Super+Comma to focus the next/previous output
##

riverctl map normal Super Period focus-output next
riverctl map normal Super Comma focus-output previous

##
## Super+Shift+{Period,Comma} to send the focused view to the next/previous output
##

riverctl map normal Super+Shift Period send-to-output next
riverctl map normal Super+Shift Comma send-to-output previous


##
### Tail: Keybind / Output / Focus
################################################################################




################################################################################
### Head: Keybind / Mode / Control
##


# Declare a passthrough mode. This mode has only a single mapping to return to
# normal mode. This makes it useful for testing a nested wayland compositor
riverctl declare-mode passthrough

# Super+F11 to enter passthrough mode
riverctl map normal Super F11 enter-mode passthrough

# Super+F11 to return to normal mode
riverctl map passthrough Super F11 enter-mode normal


##
### Tail: Keybind / Mode / Control
################################################################################




################################################################################
### Head: Keybind / Media / Control
##


# Various media key mapping examples for both normal and locked mode which do
# not have a modifier
for mode in normal locked
do
	# Eject the optical drive (well if you still have one that is)
	riverctl map $mode None XF86Eject spawn 'eject -T'

	# Control pulse audio volume with pamixer (https://github.com/cdemoulins/pamixer)
	riverctl map $mode None XF86AudioRaiseVolume  spawn 'pamixer -i 5'
	riverctl map $mode None XF86AudioLowerVolume  spawn 'pamixer -d 5'
	riverctl map $mode None XF86AudioMute		 spawn 'pamixer --toggle-mute'

	# Control MPRIS aware media players with playerctl (https://github.com/altdesktop/playerctl)
	riverctl map $mode None XF86AudioMedia spawn 'playerctl play-pause'
	riverctl map $mode None XF86AudioPlay  spawn 'playerctl play-pause'
	riverctl map $mode None XF86AudioPrev  spawn 'playerctl previous'
	riverctl map $mode None XF86AudioNext  spawn 'playerctl next'

	# Control screen backlight brightness with brightnessctl (https://github.com/Hummer12007/brightnessctl)
	riverctl map $mode None XF86MonBrightnessUp   spawn 'brightnessctl set +5%'
	riverctl map $mode None XF86MonBrightnessDown spawn 'brightnessctl set 5%-'
done


##
### Tail: Keybind / Media / Control
################################################################################




################################################################################
### Head: Keybind / Screenshot
##

riverctl map normal None Print spawn 'grimshot save screen'

riverctl map normal Super Print spawn 'grimshot save active'
riverctl map normal Control Print spawn 'grimshot save area'
riverctl map normal Alt Print spawn 'grimshot save anything'

##
### Tail: Keybind / Screenshot
################################################################################




################################################################################
### Head: Layout / Settings
##

## Set the default layout generator to be rivertile and start it.
## River will send the process group of the init executable SIGTERM on exit.
riverctl default-layout rivertile
rivertile -view-padding 6 -outer-padding 6 &


##
### Tail: Layout / Settings
################################################################################




################################################################################
### Head: Keybind / Layout / Control
##


##
## `Alt + k` and `Alt + j` to increment/decrement the main count of rivertile(1)
##

riverctl map normal Alt K send-layout-cmd rivertile "main-count +1"
riverctl map normal Alt J send-layout-cmd rivertile "main-count -1"


##
## `Alt + h` and `Alt + l` to decrease/increase the main ratio of rivertile(1)
##

riverctl map normal Alt H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal Alt L send-layout-cmd rivertile "main-ratio +0.05"


##
### Tail: Keybind / Layout / Control
################################################################################




################################################################################
### Head: Keybind / Layout / Orientation
##


##
## `Super + {Up,Right,Down,Left}` to change layout orientation
##

riverctl map normal Super Up    send-layout-cmd rivertile "main-location top"
riverctl map normal Super Right send-layout-cmd rivertile "main-location right"
riverctl map normal Super Down  send-layout-cmd rivertile "main-location bottom"
riverctl map normal Super Left  send-layout-cmd rivertile "main-location left"


##
### Tail: Keybind / Layout / Orientation
################################################################################




################################################################################
### Head: Rule / Control
##


##
## Make all views with an app-id that starts with "float" and title "foo" start floating.
##

riverctl rule-add -app-id 'float*' -title 'foo' float

##
## Make all views with app-id "bar" and any title use client-side decorations
##

riverctl rule-add -app-id "bar" csd


##
## Make views start floating.
##

riverctl rule-add -app-id 'xfce-polkit' float
riverctl rule-add -app-id 'org.pulseaudio.pavucontrol' float
riverctl rule-add -app-id 'mate-volume-control' float
riverctl rule-add -app-id 'nm-connection-editor' float


## pcmanfm-qt
riverctl rule-add -app-id 'pcmanfm-qt' -title 'Copy Files' float
riverctl rule-add -app-id 'pcmanfm-qt' -title 'Confirm to replace files' float


## thunar
riverctl rule-add -app-id 'thunar' -title 'File Operation Progress' float
riverctl rule-add -app-id 'thunar' -title 'Confirm to replace files' float


## firefox
riverctl rule-add -app-id 'org.mozilla.firefox' -title 'Picture-in-Picture' float


##
### Tail: Rule / Control
################################################################################




################################################################################
### Head: Autostart
##

~/.config/river/autostart &

##
### Tail: Autostart
################################################################################
